---
EnableDefaultLinters: true
glob: "app/**/*.{html,text,js,turbo_stream}{+*,}.erb"
linters:
  ErbSafety:
    enabled: true
  Rubocop:
      enabled: true
      rubocop_config:
        inherit_from:
          - .rubocop.yml
        Style/FrozenStringLiteralComment:
          Enabled: false
        Layout/TrailingEmptyLines:
          Enabled: false
        Layout/InitialIndentation:
          Enabled: false
        Layout/TrailingWhitespace:
          Enabled: false
        Naming/FileName:
          Enabled: false
        Layout/LineLength:
          Enabled: false
        Lint/UselessAssignment:
          Enabled: false
        Rails/OutputSafety:
          Enabled: false